name: Auto Commit and Push

on:
  schedule:
    - cron: '25 0 * * *' # This will run at 2 AM every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Important: This will fetch all history for all branches and tags.

    - name: Setup Git
      run: |
        git config user.name "maimy"
        git config user.email "m.711029@gmail.com"

    - name: Commit and push
      run: |
        git add learn_record/*
        if [ -n "$(git status --porcelain)" ]; then
          DATE=$(date -u -d 'yesterday +9 hours' +"%Y%m%d")
          git commit -m "learning record[$DATE]"
          git push
        else
          echo "No changes to commit"
        fi
